version: "3.4"
services:
  baserow_all_in_one_embedded_pg_15_auto_upgrade:
    image: baserow_all_in_one_embedded_pg_15_auto_upgrade
    build:
      dockerfile: $PWD/deploy/all-in-one-embedded-pg-15-auto-upgrade/Dockerfile
      context: $PWD
      args:
        # We allow configuring the UID/GID here so you can run as the dev's actual user
        # reducing the chance the containers screw up the bind mounted folders.
        UID: $UID
        GID: $GID
    volumes:
      - baserow_all_in_one_data:/baserow/data
    stdin_open: true
    tty: true
volumes:
  baserow_all_in_one_data:
