version: "3.4"
services:
  # A dev / testing /example compose file for quickly setting up an all in one
  baserow_all_in_one_embedded_pg_11:
    image: baserow_all_in_one_embedded_pg_11
    build:
      dockerfile: $PWD/deploy/all-in-one-embedded-pg-11/Dockerfile
      context: $PWD
      args:
        # We allow configuring the UID/GID here so you can run as the dev's actual user
        # reducing the chance the containers screw up the bind mounted folders.
        UID: $UID
        GID: $GID
    environment:
      EMAIL_SMTP: 'yes'
      EMAIL_SMTP_HOST: 'mailhog'
      EMAIL_SMTP_PORT: '1025'
      BASEROW_PUBLIC_URL:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - baserow_all_in_one_data:/baserow/data
    healthcheck:
      test: [ "CMD-SHELL", "/baserow/backend/docker/docker-entrypoint.sh backend-healthcheck" ]
      interval: 10s
      timeout: 5s
      retries: 5
    stdin_open: true
    tty: true
  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - "8025:8025" # web ui
volumes:
  baserow_all_in_one_data:
